### ISSUE TITLE
Respect WP_CONTENT_DIR when checking for modified files

### ISSUE THREAD

**Issue by sellcom** [FernleafSystems/Shield#11]
We receive daily warnings that Core WP files have been modified, like these:
The following official WordPress core files are missing from your site:
- wp-content/themes/index.php (WordPress.org source file)
- wp-content/plugins/index.php (WordPress.org source file)
- wp-content/index.php (WordPress.org source file)

These files don't actually exist, b/c we use an alternate directory for wp-content (a very effective security measure against script kiddies):
/** Tweak the place where user content and plugins are stored **/
define( 'WP_CONTENT_DIR', $_SERVER['DOCUMENT_ROOT'] . '/wpZZZ-content' );
define( 'WP_CONTENT_URL', 'http://www.xyz.com/wpZZZ-content');

Please check WP_CONTENT_DIR when looking for modified files.

**Comment by paulgoodchild** [comment]
This will be fixed by completely excluding the WP-CONTENT directory altogether.  We're already excluding the plugins, themes, and languages.  There's no much left there.
