### ISSUE TITLE
Duplicate SUBJECT Header in warning email

### ISSUE THREAD

**Issue by sellcom** [FernleafSystems/Shield#12]
Our WP core file warning email contains a duplicate SUBJECT header line:

Fri, 11 Mar 2016 11:07:37 -0000
To: xyz@xyz.com
Subject: Warning - Core WordPress Files(s) Discovered That May Have Been Modified.
X-PHP-Originating-Script: 4000:class-phpmailer.php
Date: Fri, 11 Mar 2016 11:07:37 +0000
From: - WordPress Security Firewall < xyz@xyz.com >
Message-ID: <f35a28bb8403b0477795c22c5d6f92fb@xxxxxxxxxxxxxxxxxxxxx>
X-Mailer: PHPMailer 5.2.14 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Subject: Warning - Core WordPress Files(s) Discovered That May Have Been Modified.
X-Mailer: PHP/5.6.17-0+deb8u1
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

**Comment by paulgoodchild** [comment]
Are you definitely on the latest version of the plugin on this site?  v4.17 has improvements to the email system to prevent this from happening

**Comment by sellcom** [comment]
This email was sent from 4.16.2; I'll upgrade. Thanks!
