### ISSUE TITLE
Site listed in warning email can be empty

### ISSUE THREAD

**Issue by sellcom** [FernleafSystems/Shield#13]
In the case where users have removed the Site Title from WP Settings, there's no link or indication as to which site has a problem. Perhaps default to site URL, and/or make sure there's always a link in every Shield email to the WP Site URL in question. Example email rec'd:
----------------------
Subject: Warning - Core WordPress Files(s) Discovered That May Have Been Modified.
WordPress Security Firewall has detected files on your site with potential problems.
This is part of the Hack Protection feature for the WordPress Core File Scanner. [More Info]
Site - 
Details for the problem files are below:
...
----------------------

**Comment by paaljoachim** [comment]
General settings

Existing:

![screen shot 2018-11-09 at 17 47 21](https://user-images.githubusercontent.com/5323259/48276139-921d3a00-e447-11e8-8fcd-06bc63f1e3b1.png)

Add a dash of air:

![security-shield-air](https://user-images.githubusercontent.com/5323259/48276226-cbee4080-e447-11e8-930f-e23da52871b2.jpg)
